enabled = "yes"

[settings]
url_prefix = "/auth"
#subdomain = ""
#url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/auth/static"

#[session]
#login_session = "yes"
