# Updates the Flask app config with the variables below.
# If any variable below does not exist in the standard Flask env vars it is created and will be accessible using
# app.config["YOUR_VAR_NAME"]. All variables defined below will be capitalised when imported.

[flask]
APP_NAME = "app"
VERSION = "0.0.1"
SECRET_KEY = "16b1e894698ac22539b5898d3e020ea5c1ca0b1fb82f89d2"
DEBUG = false
TESTING = false
SESSION_TIME = 480
ERROR_404_HELP = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXPLAIN_TEMPLATE_LOADING = false
RESET_DB = true

# [database.main] is loaded as SQLALCHEMY_DATABASE_URI
# type = mysql / postgresql / sqlite
# if type = sqlite, config parser will ignore username and password
[database]
[database.main]
enabled = true
type = "sqlite"
database_name = "database"
location = "db"
port = ""
username = "user"
password = "password"

[session]
user_id = 0
passport = 0
authenticated = false
