# Updates the Flask app config with the variables below.
# If any variable below does not exist in the standard Flask env vars it is created and will be accessible using
# app.config["YOUR_VAR_NAME"]. All variables defined below will be capitalised when imported.

[flask]
APP_NAME = "easyquest"
VERSION = "1.0.0"
SECRET_KEY = "J3UsrFgrYfryeRdmYM5WMeCZM8tRWcmpsRRfqsx5m4ZbEFAfmDYmVyqDeWdrFEXVPpKAE6VBZfJTmvqB"
DEBUG = false
TESTING = false
SESSION_TIME = 480
ERROR_404_HELP = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXPLAIN_TEMPLATE_LOADING = false
RESET_DB = true

# [database.main] is loaded as SQLALCHEMY_DATABASE_URI
# type = mysql / postgresql / sqlite
# if type = sqlite, config parser will ignore username and password
[database]
[database.main]
enabled = true
type = "sqlite"
database_name = "database"
location = "db"
port = ""
username = "user"
password = "password"

[session]
user_id = 0
user_type = 0
permissions = []
passport = 0
authenticated = false
temp = { }
