enabled = "yes"

[settings]
url_prefix = "/login"
subdomain = ""
url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/login/static"

[session]
login_session = "yes"

